# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    kr4_position_conctroller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kr4_position_conctroller:
  ros__parameters:
    joints:
      - joint1
      - join2
      - joint3
      - joint4
      - joint5
      - join6